package WasteLibrary

const (
	RESULT_FAIL = "FAIL"
	RESULT_OK   = "OK"
	RESULT_NOT  = "NOT"
)

const (
	STATU_ACTIVE  = "ACTIVE"
	STATU_PASSIVE = "PASSIVE"
)

const (
	HTTP_HEADER = "HEADER"
	HTTP_DATA   = "DATA"
	HTTP_OPTYPE = "OPTYPE"
	HTTP_TOKEN  = "TOKEN"
)

const (
	LOGGER_CONTAINER = "CONTAINER"
	LOGGER_LOGTYPE   = "LOGTYPE"
	LOGGER_FUNC      = "FUNC"
	LOGGER_LOG       = "LOG"
	LOGGER_DEBUG     = "DEBUG"
	LOGGER_ERROR     = "ERROR"
	LOGGER_INFO      = "INFO"
)

const (
	OPTYPE_APP            = "APP"
	OPTYPE_CONN           = "CONN"
	OPTYPE_READER         = "READER"
	OPTYPE_CAM            = "CAM"
	OPTYPE_GPS            = "GPS"
	OPTYPE_RF             = "RF"
	OPTYPE_NONE           = "NONE"
	OPTYPE_STATUS         = "STATUS"
	OPTYPE_THERM          = "THERM"
	OPTYPE_CUSTOMERCONFIG = "CUSTOMERCONFIG"
	OPTYPE_ADMINCONFIG    = "ADMINCONFIG"
	OPTYPE_LOCALCONFIG    = "LOCALCONFIG"
	OPTYPE_USER           = "USER"
	OPTYPE_DEVICE         = "DEVICE"
	OPTYPE_SENS           = "SENS"
	OPTYPE_ATMP           = "ATMP"
	OPTYPE_AGPS           = "AGPS"
	OPTYPE_TYPE           = "TYPE"
	OPTYPE_TAG            = "TAG"
	OPTYPE_ARVENTO        = "ARVENTO"
	OPTYPE_CUSTOMER       = "CUSTOMER"
)

const (
	CONTAINER_STATU_NONE  = "NONE"
	CONTAINER_STATU_EMPTY = "EMPTY"
	CONTAINER_STATU_HALF  = "HALF"
	CONTAINER_STATU_FULL  = "FULL"
	CONTAINER_STATU_ERROR = "ERROR"
)

const (
	ULT_STATU_NONE  = "NONE"
	ULT_STATU_EMPTY = "EMPTY"
	ULT_STATU_HALF  = "HALF"
	ULT_STATU_FULL  = "FULL"
	ULT_STATU_ERROR = "ERROR"
)

const (
	RFID_READER_OKBIT    = "5379"
	RFID_READER_STARTBIT = "4354"
	RFID_READER_CHECKBIT = "45"
	RFID_TAG_PATTERN     = "AFA09012018AFA"
)

const (
	APPTYPE_ULT    = "ULT"
	APPTYPE_RFID   = "RFID"
	APPTYPE_RECY   = "RECY"
	APPTYPE_ADMIN  = "ADMIN"
	APPTYPE_AFATEK = "AFATEK"
)
const (
	BASETYPE_CUSTOMER = "CUSTOMER"
	BASETYPE_DEVICE   = "DEVICE"
	BASETYPE_TAG      = "TAG"
	BASETYPE_USER     = "USER"
)

const (
	ALARM_NONE = "NONE"
	ALARM_ATMP = "THERM"
	ALARM_AGPS = "GPS"
)

const (
	ALARM_STATU_NONE  = "NONE"
	ALARM_STATU_ALARM = "ALARM"
)
const (
	THERM_STATU_NONE   = "NONE"
	THERM_STATU_NORMAL = "NORMAL"
	THERM_STATU_HIGH   = "HIGH"
)

const (
	BATTERY_STATU_NONE   = "NONE"
	BATTERY_STATU_NORMAL = "NORMAL"
	BATTERY_STATU_LOW    = "LOW"
)

const (
	REDIS_SERIAL_DEVICE           = "serial-device"
	REDIS_DEVICES                 = "devices"
	REDIS_CUSTOMER_TAGS           = "customer-tags"
	REDIS_CUSTOMER_DEVICES        = "customer-devices"
	REDIS_CUSTOMERS               = "customers"
	REDIS_CUSTOMER_CUSTOMERCONFIG = "customer-customerconfig"
	REDIS_CUSTOMER_ADMINCONFIG    = "customer-adminconfig"
	REDIS_CUSTOMER_LOCALCONFIG    = "customer-localconfig"
	REDIS_CUSTOMER_LINK           = "customer-link"
	REDIS_USERS                   = "users"
	REDIS_CUSTOMER_USERS          = "customer-users"
	REDIS_HASHKEY                 = "HASHKEY"
	REDIS_SUBKEY                  = "SUBKEY"
	REDIS_KEYVALUE                = "KEYVALUE"
)

const (
	USER_GUEST  = "GUEST"
	USER_ADMIN  = "ADMIN"
	USER_REPORT = "REPORT"
)
